services:
  api:
    container_name: "backend-api"
    build:
      context: .
    image: "backend-app"
    command: /app/runserver.sh
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - .:/app